name: RivCore
main: me.rivwhall05.RivCore.core.Main
author: rivwhall05
version: 1.0
description: RivCore - A bunch of commands.
commands:
   say:
      description: BLOCKING SAY
   lol:
      description: Lol
   rainbow:
      description: Its a rainbow YAAAY
   lovedoge:
      description: Awww its sooo cute!
   alert:
      description: Alert
      permission: rivcore.alert
      permission-message: You cannot do an alert!
